- name: create roboshhop user
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download {{component}} application #here component is variable
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: extract {{component}} application
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes